application: meu-bus-tempo-real
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: views/layout/css

- url: /js
  static_dir: views/layout/js

- url: .*
  script: main.app

